import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';
// Generated by `flutterfire configure` (see SETUP.md step 4):
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Preload the display/body/Arabic faces before the first frame so text
  // renders sharp immediately — no flash of fallback font (FOUT). Fonts are
  // disk-cached after the first fetch; the timeout keeps a cold offline
  // launch from ever blocking startup.
  try {
    await GoogleFonts.pendingFonts([
      GoogleFonts.fraunces(),
      GoogleFonts.inter(),
      GoogleFonts.amiri(),
    ]).timeout(const Duration(seconds: 3));
  } catch (_) {
    // Offline / slow network — fall back to system font for this launch.
  }

  runApp(const ProviderScope(child: IkhlasApp()));
}

class IkhlasApp extends ConsumerWidget {
  const IkhlasApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);
    return MaterialApp.router(
      title: 'Ikhlas',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),   // 2d — light sage ceremonial
      darkTheme: AppTheme.dark(), // 2a–2c — emerald + gold
      themeMode: ThemeMode.dark,  // dark-first at launch (spec's primary system)
      routerConfig: router,
    );
  }
}
