import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';
// Generated by `flutterfire configure` (see SETUP.md step 4):
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const ProviderScope(child: IkhlasApp()));
}

class IkhlasApp extends ConsumerWidget {
  const IkhlasApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);
    return MaterialApp.router(
      title: 'Ikhlas',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),   // 2d — light sage ceremonial
      darkTheme: AppTheme.dark(), // 2a–2c — emerald + gold
      themeMode: ThemeMode.dark,  // dark-first at launch (spec's primary system)
      routerConfig: router,
    );
  }
}
