import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';
// Generated by `flutterfire configure` (see SETUP.md step 4):
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // Light 2d theme → dark status-bar icons on the sage ground.
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.dark,
    statusBarBrightness: Brightness.light,
  ));
  // Fonts are bundled as assets (see pubspec) — sharp on the first frame,
  // no runtime fetch, works fully offline.
  runApp(const ProviderScope(child: IkhlasApp()));
}

class IkhlasApp extends ConsumerWidget {
  const IkhlasApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);
    return MaterialApp.router(
      title: 'Ikhlaas',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),   // 2d — light sage ceremonial (whole app)
      darkTheme: AppTheme.light(), // pinned light — no dark variant at launch
      themeMode: ThemeMode.light,
      routerConfig: router,
    );
  }
}
