// Self-contained location data for country -> state -> city dropdowns
// and a country list for nationality selection.
//
// No imports, no dependencies on other project files. Everything is const.

/// List of countries. India first, then alphabetical.
const List<String> kCountries = <String>[
  'India',
  'Afghanistan',
  'Algeria',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Belgium',
  'Brunei',
  'Canada',
  'China',
  'Denmark',
  'Egypt',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Germany',
  'Ghana',
  'Greece',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Italy',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kuwait',
  'Kyrgyzstan',
  'Lebanon',
  'Libya',
  'Malaysia',
  'Maldives',
  'Mauritius',
  'Morocco',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Palestine',
  'Philippines',
  'Portugal',
  'Qatar',
  'Russia',
  'Saudi Arabia',
  'Senegal',
  'Singapore',
  'Somalia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Sweden',
  'Switzerland',
  'Syria',
  'Tanzania',
  'Thailand',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uzbekistan',
  'Yemen',
];

/// States / provinces / regions keyed by country.
/// Countries without a listed subdivision map to an empty list; the UI will
/// then let the user type a value or skip it.
const Map<String, List<String>> kStatesByCountry = <String, List<String>>{
  'India': <String>[
    // 28 states
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
    // 8 union territories
    'Andaman and Nicobar Islands',
    'Chandigarh',
    'Dadra and Nagar Haveli and Daman and Diu',
    'Delhi',
    'Jammu and Kashmir',
    'Ladakh',
    'Lakshadweep',
    'Puducherry',
  ],
  'Pakistan': <String>[
    'Punjab',
    'Sindh',
    'Khyber Pakhtunkhwa',
    'Balochistan',
    'Gilgit-Baltistan',
    'Azad Jammu and Kashmir',
    'Islamabad Capital Territory',
  ],
  'Bangladesh': <String>[
    'Dhaka',
    'Chittagong',
    'Rajshahi',
    'Khulna',
    'Barisal',
    'Sylhet',
    'Rangpur',
    'Mymensingh',
  ],
  'United Arab Emirates': <String>[
    'Abu Dhabi',
    'Dubai',
    'Sharjah',
    'Ajman',
    'Umm Al Quwain',
    'Ras Al Khaimah',
    'Fujairah',
  ],
  'Saudi Arabia': <String>[
    'Riyadh',
    'Makkah',
    'Madinah',
    'Eastern Province',
    'Asir',
    'Tabuk',
    'Qassim',
    'Hail',
    'Jazan',
    'Najran',
    'Al Bahah',
    'Al Jawf',
    'Northern Borders',
  ],
  'United States': <String>[
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
    'District of Columbia',
  ],
  'United Kingdom': <String>[
    'England',
    'Scotland',
    'Wales',
    'Northern Ireland',
  ],
  'Canada': <String>[
    'Alberta',
    'British Columbia',
    'Manitoba',
    'New Brunswick',
    'Newfoundland and Labrador',
    'Nova Scotia',
    'Ontario',
    'Prince Edward Island',
    'Quebec',
    'Saskatchewan',
    'Northwest Territories',
    'Nunavut',
    'Yukon',
  ],
  'Australia': <String>[
    'New South Wales',
    'Victoria',
    'Queensland',
    'Western Australia',
    'South Australia',
    'Tasmania',
    'Australian Capital Territory',
    'Northern Territory',
  ],
  'Malaysia': <String>[
    'Johor',
    'Kedah',
    'Kelantan',
    'Malacca',
    'Negeri Sembilan',
    'Pahang',
    'Penang',
    'Perak',
    'Perlis',
    'Sabah',
    'Sarawak',
    'Selangor',
    'Terengganu',
    'Kuala Lumpur',
    'Labuan',
    'Putrajaya',
  ],
  'Qatar': <String>[
    'Doha',
    'Al Rayyan',
    'Al Wakrah',
    'Al Khor',
    'Umm Salal',
    'Al Daayen',
    'Al Shamal',
    'Al Shahaniya',
  ],
  'Kuwait': <String>[
    'Al Asimah',
    'Hawalli',
    'Farwaniya',
    'Mubarak Al-Kabeer',
    'Ahmadi',
    'Jahra',
  ],
  'Bahrain': <String>[
    'Capital',
    'Muharraq',
    'Northern',
    'Southern',
  ],
  'Oman': <String>[
    'Muscat',
    'Dhofar',
    'Musandam',
    'Al Buraimi',
    'Al Dakhiliyah',
    'Al Batinah North',
    'Al Batinah South',
    'Al Sharqiyah North',
    'Al Sharqiyah South',
    'Al Dhahirah',
    'Al Wusta',
  ],
  'Sri Lanka': <String>[
    'Western',
    'Central',
    'Southern',
    'Northern',
    'Eastern',
    'North Western',
    'North Central',
    'Uva',
    'Sabaragamuwa',
  ],
  'Indonesia': <String>[
    'Jakarta',
    'West Java',
    'Central Java',
    'East Java',
    'Banten',
    'Yogyakarta',
    'Bali',
    'North Sumatra',
    'West Sumatra',
    'South Sulawesi',
    'Aceh',
  ],
  'Turkey': <String>[
    'Istanbul',
    'Ankara',
    'Izmir',
    'Bursa',
    'Antalya',
    'Adana',
    'Konya',
    'Gaziantep',
  ],
  'Egypt': <String>[
    'Cairo',
    'Giza',
    'Alexandria',
    'Dakahlia',
    'Sharqia',
    'Qalyubia',
    'Gharbia',
    'Port Said',
    'Suez',
    'Aswan',
    'Luxor',
  ],
  'Nigeria': <String>[
    'Lagos',
    'Kano',
    'Kaduna',
    'Rivers',
    'Oyo',
    'Abuja Federal Capital Territory',
    'Sokoto',
    'Borno',
    'Katsina',
  ],
  'South Africa': <String>[
    'Gauteng',
    'Western Cape',
    'KwaZulu-Natal',
    'Eastern Cape',
    'Free State',
    'Limpopo',
    'Mpumalanga',
    'North West',
    'Northern Cape',
  ],
  'Maldives': <String>[
    'Male',
    'Addu City',
    'Fuvahmulah',
    'Kulhudhuffushi',
  ],
  'Singapore': <String>[],
  'Germany': <String>[
    'Bavaria',
    'Baden-Wurttemberg',
    'Berlin',
    'Hamburg',
    'Hesse',
    'North Rhine-Westphalia',
    'Lower Saxony',
    'Saxony',
  ],
  'France': <String>[
    'Ile-de-France',
    'Provence-Alpes-Cote d\'Azur',
    'Auvergne-Rhone-Alpes',
    'Nouvelle-Aquitaine',
    'Occitanie',
    'Grand Est',
    'Hauts-de-France',
    'Normandy',
  ],
};

/// Major cities keyed by "Country|State".
/// India is covered thoroughly. Non-India entries are provided where known.
const Map<String, List<String>> kCitiesByState = <String, List<String>>{
  // ---- India ----
  'India|Andhra Pradesh': <String>[
    'Visakhapatnam',
    'Vijayawada',
    'Guntur',
    'Nellore',
    'Kurnool',
    'Rajahmundry',
    'Tirupati',
    'Kakinada',
    'Kadapa',
    'Anantapur',
  ],
  'India|Arunachal Pradesh': <String>[
    'Itanagar',
    'Naharlagun',
    'Pasighat',
    'Tawang',
    'Ziro',
    'Bomdila',
    'Tezu',
  ],
  'India|Assam': <String>[
    'Guwahati',
    'Silchar',
    'Dibrugarh',
    'Jorhat',
    'Nagaon',
    'Tinsukia',
    'Tezpur',
    'Bongaigaon',
  ],
  'India|Bihar': <String>[
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Muzaffarpur',
    'Darbhanga',
    'Purnia',
    'Arrah',
    'Begusarai',
    'Katihar',
    'Chapra',
  ],
  'India|Chhattisgarh': <String>[
    'Raipur',
    'Bhilai',
    'Bilaspur',
    'Korba',
    'Durg',
    'Rajnandgaon',
    'Jagdalpur',
    'Raigarh',
  ],
  'India|Goa': <String>[
    'Panaji',
    'Margao',
    'Vasco da Gama',
    'Mapusa',
    'Ponda',
    'Bicholim',
  ],
  'India|Gujarat': <String>[
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Gandhinagar',
    'Junagadh',
    'Anand',
    'Nadiad',
  ],
  'India|Haryana': <String>[
    'Faridabad',
    'Gurugram',
    'Panipat',
    'Ambala',
    'Yamunanagar',
    'Rohtak',
    'Hisar',
    'Karnal',
    'Sonipat',
    'Panchkula',
  ],
  'India|Himachal Pradesh': <String>[
    'Shimla',
    'Solan',
    'Dharamshala',
    'Mandi',
    'Kullu',
    'Bilaspur',
    'Hamirpur',
    'Una',
  ],
  'India|Jharkhand': <String>[
    'Ranchi',
    'Jamshedpur',
    'Dhanbad',
    'Bokaro',
    'Deoghar',
    'Hazaribagh',
    'Giridih',
    'Ramgarh',
  ],
  'India|Karnataka': <String>[
    'Bengaluru',
    'Mysuru',
    'Hubli-Dharwad',
    'Mangaluru',
    'Belagavi',
    'Kalaburagi',
    'Davanagere',
    'Ballari',
    'Vijayapura',
    'Shivamogga',
    'Tumakuru',
    'Udupi',
  ],
  'India|Kerala': <String>[
    'Thiruvananthapuram',
    'Kochi',
    'Kozhikode',
    'Thrissur',
    'Kollam',
    'Kannur',
    'Kottayam',
    'Malappuram',
    'Palakkad',
    'Alappuzha',
    'Pathanamthitta',
    'Kasaragod',
  ],
  'India|Madhya Pradesh': <String>[
    'Bhopal',
    'Indore',
    'Jabalpur',
    'Gwalior',
    'Ujjain',
    'Sagar',
    'Dewas',
    'Satna',
    'Ratlam',
    'Rewa',
  ],
  'India|Maharashtra': <String>[
    'Mumbai',
    'Pune',
    'Nagpur',
    'Nashik',
    'Chhatrapati Sambhajinagar',
    'Thane',
    'Solapur',
    'Amravati',
    'Kolhapur',
    'Navi Mumbai',
    'Sangli',
    'Jalgaon',
  ],
  'India|Manipur': <String>[
    'Imphal',
    'Thoubal',
    'Bishnupur',
    'Churachandpur',
    'Kakching',
    'Ukhrul',
  ],
  'India|Meghalaya': <String>[
    'Shillong',
    'Tura',
    'Jowai',
    'Nongstoin',
    'Williamnagar',
    'Baghmara',
  ],
  'India|Mizoram': <String>[
    'Aizawl',
    'Lunglei',
    'Champhai',
    'Serchhip',
    'Kolasib',
    'Saiha',
  ],
  'India|Nagaland': <String>[
    'Kohima',
    'Dimapur',
    'Mokokchung',
    'Tuensang',
    'Wokha',
    'Zunheboto',
  ],
  'India|Odisha': <String>[
    'Bhubaneswar',
    'Cuttack',
    'Rourkela',
    'Berhampur',
    'Sambalpur',
    'Puri',
    'Balasore',
    'Baripada',
  ],
  'India|Punjab': <String>[
    'Ludhiana',
    'Amritsar',
    'Jalandhar',
    'Patiala',
    'Bathinda',
    'Mohali',
    'Hoshiarpur',
    'Pathankot',
    'Moga',
    'Firozpur',
  ],
  'India|Rajasthan': <String>[
    'Jaipur',
    'Jodhpur',
    'Kota',
    'Bikaner',
    'Ajmer',
    'Udaipur',
    'Bhilwara',
    'Alwar',
    'Sikar',
    'Sri Ganganagar',
  ],
  'India|Sikkim': <String>[
    'Gangtok',
    'Namchi',
    'Gyalshing',
    'Mangan',
    'Rangpo',
    'Singtam',
  ],
  'India|Tamil Nadu': <String>[
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli',
    'Salem',
    'Tirunelveli',
    'Tiruppur',
    'Erode',
    'Vellore',
    'Thoothukudi',
    'Dindigul',
    'Thanjavur',
  ],
  'India|Telangana': <String>[
    'Hyderabad',
    'Warangal',
    'Nizamabad',
    'Karimnagar',
    'Khammam',
    'Ramagundam',
    'Mahbubnagar',
    'Nalgonda',
  ],
  'India|Tripura': <String>[
    'Agartala',
    'Udaipur',
    'Dharmanagar',
    'Kailashahar',
    'Belonia',
    'Ambassa',
  ],
  'India|Uttar Pradesh': <String>[
    'Lucknow',
    'Kanpur',
    'Ghaziabad',
    'Agra',
    'Varanasi',
    'Meerut',
    'Prayagraj',
    'Noida',
    'Bareilly',
    'Aligarh',
    'Moradabad',
    'Gorakhpur',
  ],
  'India|Uttarakhand': <String>[
    'Dehradun',
    'Haridwar',
    'Roorkee',
    'Haldwani',
    'Rudrapur',
    'Kashipur',
    'Rishikesh',
    'Nainital',
  ],
  'India|West Bengal': <String>[
    'Kolkata',
    'Howrah',
    'Asansol',
    'Siliguri',
    'Durgapur',
    'Bardhaman',
    'Malda',
    'Kharagpur',
    'Darjeeling',
    'Haldia',
  ],
  'India|Andaman and Nicobar Islands': <String>[
    'Port Blair',
    'Diglipur',
    'Mayabunder',
    'Rangat',
    'Car Nicobar',
  ],
  'India|Chandigarh': <String>[
    'Chandigarh',
  ],
  'India|Dadra and Nagar Haveli and Daman and Diu': <String>[
    'Silvassa',
    'Daman',
    'Diu',
  ],
  'India|Delhi': <String>[
    'New Delhi',
    'Delhi',
    'Dwarka',
    'Rohini',
    'Saket',
    'Karol Bagh',
  ],
  'India|Jammu and Kashmir': <String>[
    'Srinagar',
    'Jammu',
    'Anantnag',
    'Baramulla',
    'Sopore',
    'Udhampur',
    'Kathua',
  ],
  'India|Ladakh': <String>[
    'Leh',
    'Kargil',
    'Diskit',
    'Nubra',
  ],
  'India|Lakshadweep': <String>[
    'Kavaratti',
    'Agatti',
    'Amini',
    'Andrott',
    'Minicoy',
  ],
  'India|Puducherry': <String>[
    'Puducherry',
    'Karaikal',
    'Yanam',
    'Mahe',
  ],

  // ---- Pakistan ----
  'Pakistan|Punjab': <String>[
    'Lahore',
    'Faisalabad',
    'Rawalpindi',
    'Multan',
    'Gujranwala',
    'Sialkot',
    'Bahawalpur',
    'Sargodha',
  ],
  'Pakistan|Sindh': <String>[
    'Karachi',
    'Hyderabad',
    'Sukkur',
    'Larkana',
    'Nawabshah',
    'Mirpur Khas',
  ],
  'Pakistan|Khyber Pakhtunkhwa': <String>[
    'Peshawar',
    'Mardan',
    'Mingora',
    'Kohat',
    'Abbottabad',
    'Bannu',
  ],
  'Pakistan|Balochistan': <String>[
    'Quetta',
    'Turbat',
    'Khuzdar',
    'Gwadar',
    'Chaman',
  ],
  'Pakistan|Islamabad Capital Territory': <String>[
    'Islamabad',
  ],

  // ---- Bangladesh ----
  'Bangladesh|Dhaka': <String>[
    'Dhaka',
    'Gazipur',
    'Narayanganj',
    'Tangail',
    'Narsingdi',
  ],
  'Bangladesh|Chittagong': <String>[
    'Chittagong',
    'Comilla',
    'Cox\'s Bazar',
    'Feni',
    'Brahmanbaria',
  ],
  'Bangladesh|Sylhet': <String>[
    'Sylhet',
    'Moulvibazar',
    'Habiganj',
    'Sunamganj',
  ],
  'Bangladesh|Rajshahi': <String>[
    'Rajshahi',
    'Bogra',
    'Pabna',
    'Sirajganj',
  ],
  'Bangladesh|Khulna': <String>[
    'Khulna',
    'Jessore',
    'Kushtia',
    'Satkhira',
  ],

  // ---- United Arab Emirates ----
  'United Arab Emirates|Dubai': <String>[
    'Dubai',
    'Jebel Ali',
    'Hatta',
  ],
  'United Arab Emirates|Abu Dhabi': <String>[
    'Abu Dhabi',
    'Al Ain',
    'Ruwais',
    'Madinat Zayed',
  ],
  'United Arab Emirates|Sharjah': <String>[
    'Sharjah',
    'Khor Fakkan',
    'Kalba',
  ],

  // ---- Saudi Arabia ----
  'Saudi Arabia|Riyadh': <String>[
    'Riyadh',
    'Al Kharj',
    'Al Majma\'ah',
    'Ad Diriyah',
  ],
  'Saudi Arabia|Makkah': <String>[
    'Makkah',
    'Jeddah',
    'Taif',
    'Rabigh',
  ],
  'Saudi Arabia|Madinah': <String>[
    'Madinah',
    'Yanbu',
    'Al Ula',
  ],
  'Saudi Arabia|Eastern Province': <String>[
    'Dammam',
    'Al Khobar',
    'Dhahran',
    'Jubail',
    'Al Ahsa',
    'Hafar Al-Batin',
  ],

  // ---- United States ----
  'United States|California': <String>[
    'Los Angeles',
    'San Francisco',
    'San Diego',
    'San Jose',
    'Sacramento',
    'Fresno',
    'Oakland',
  ],
  'United States|New York': <String>[
    'New York City',
    'Buffalo',
    'Rochester',
    'Albany',
    'Syracuse',
    'Yonkers',
  ],
  'United States|Texas': <String>[
    'Houston',
    'Dallas',
    'Austin',
    'San Antonio',
    'Fort Worth',
    'El Paso',
  ],
  'United States|Illinois': <String>[
    'Chicago',
    'Aurora',
    'Naperville',
    'Springfield',
    'Peoria',
  ],
  'United States|New Jersey': <String>[
    'Newark',
    'Jersey City',
    'Paterson',
    'Edison',
    'Elizabeth',
  ],

  // ---- United Kingdom ----
  'United Kingdom|England': <String>[
    'London',
    'Birmingham',
    'Manchester',
    'Leeds',
    'Liverpool',
    'Bristol',
    'Sheffield',
    'Leicester',
    'Bradford',
  ],
  'United Kingdom|Scotland': <String>[
    'Glasgow',
    'Edinburgh',
    'Aberdeen',
    'Dundee',
    'Inverness',
  ],
  'United Kingdom|Wales': <String>[
    'Cardiff',
    'Swansea',
    'Newport',
    'Wrexham',
  ],
  'United Kingdom|Northern Ireland': <String>[
    'Belfast',
    'Londonderry',
    'Lisburn',
    'Newry',
  ],

  // ---- Canada ----
  'Canada|Ontario': <String>[
    'Toronto',
    'Ottawa',
    'Mississauga',
    'Brampton',
    'Hamilton',
    'London',
    'Markham',
  ],
  'Canada|Quebec': <String>[
    'Montreal',
    'Quebec City',
    'Laval',
    'Gatineau',
    'Longueuil',
  ],
  'Canada|British Columbia': <String>[
    'Vancouver',
    'Surrey',
    'Burnaby',
    'Richmond',
    'Victoria',
  ],
  'Canada|Alberta': <String>[
    'Calgary',
    'Edmonton',
    'Red Deer',
    'Lethbridge',
  ],

  // ---- Australia ----
  'Australia|New South Wales': <String>[
    'Sydney',
    'Newcastle',
    'Wollongong',
    'Central Coast',
  ],
  'Australia|Victoria': <String>[
    'Melbourne',
    'Geelong',
    'Ballarat',
    'Bendigo',
  ],
  'Australia|Queensland': <String>[
    'Brisbane',
    'Gold Coast',
    'Townsville',
    'Cairns',
  ],

  // ---- Malaysia ----
  'Malaysia|Kuala Lumpur': <String>[
    'Kuala Lumpur',
  ],
  'Malaysia|Selangor': <String>[
    'Shah Alam',
    'Petaling Jaya',
    'Subang Jaya',
    'Klang',
  ],
  'Malaysia|Penang': <String>[
    'George Town',
    'Butterworth',
    'Bukit Mertajam',
  ],

  // ---- Qatar ----
  'Qatar|Doha': <String>[
    'Doha',
  ],
  'Qatar|Al Rayyan': <String>[
    'Al Rayyan',
  ],

  // ---- Kuwait ----
  'Kuwait|Al Asimah': <String>[
    'Kuwait City',
  ],
  'Kuwait|Hawalli': <String>[
    'Hawalli',
    'Salmiya',
  ],

  // ---- Oman ----
  'Oman|Muscat': <String>[
    'Muscat',
    'Muttrah',
    'Seeb',
    'Bawshar',
  ],
  'Oman|Dhofar': <String>[
    'Salalah',
  ],

  // ---- Sri Lanka ----
  'Sri Lanka|Western': <String>[
    'Colombo',
    'Sri Jayawardenepura Kotte',
    'Negombo',
    'Moratuwa',
    'Dehiwala-Mount Lavinia',
  ],
  'Sri Lanka|Central': <String>[
    'Kandy',
    'Matale',
    'Nuwara Eliya',
  ],

  // ---- Indonesia ----
  'Indonesia|Jakarta': <String>[
    'Jakarta',
  ],
  'Indonesia|West Java': <String>[
    'Bandung',
    'Bekasi',
    'Depok',
    'Bogor',
  ],
  'Indonesia|East Java': <String>[
    'Surabaya',
    'Malang',
    'Kediri',
  ],

  // ---- Turkey ----
  'Turkey|Istanbul': <String>[
    'Istanbul',
  ],
  'Turkey|Ankara': <String>[
    'Ankara',
  ],

  // ---- Egypt ----
  'Egypt|Cairo': <String>[
    'Cairo',
    'Nasr City',
    'Helwan',
  ],
  'Egypt|Alexandria': <String>[
    'Alexandria',
  ],

  // ---- Nigeria ----
  'Nigeria|Lagos': <String>[
    'Lagos',
    'Ikeja',
    'Ikorodu',
  ],
  'Nigeria|Kano': <String>[
    'Kano',
  ],

  // ---- South Africa ----
  'South Africa|Gauteng': <String>[
    'Johannesburg',
    'Pretoria',
    'Soweto',
    'Benoni',
  ],
  'South Africa|Western Cape': <String>[
    'Cape Town',
    'Stellenbosch',
    'Paarl',
  ],
  'South Africa|KwaZulu-Natal': <String>[
    'Durban',
    'Pietermaritzburg',
    'Newcastle',
  ],
};

/// Returns the list of states/provinces for [country], or an empty list.
List<String> statesFor(String? country) => kStatesByCountry[country] ?? const <String>[];

/// Returns the list of cities for [country] and [state], or an empty list.
List<String> citiesFor(String? country, String? state) =>
    kCitiesByState['$country|$state'] ?? const <String>[];
